#################################################
# common
#################################################

mysql_1: &mysql_1
  host: ubuntu.a.com
  port: 3306
  user: root
  passwd: 1234
  schema: cx

#################################################
# server
#################################################

chat_server:
  id: 1
  type: 1
  name: chat_room
  listen:
    - id: 1
      ip: 127.0.0.1
      port: 6001
  connect:
    - id: 1
      ip: 127.0.0.1
      port: 6091
  db:
    mysql: *mysql_1

api_service:
  id: 1
  type: 1
  name: api_service
  listen:
    - id: 1
      ip: 127.0.0.1
      port: 6051
  connect:
    - id: 1
      ip: 127.0.0.1
      port: 6091

master_server:
  id: 1
  type: 1
  name: master
  listen:
    - id: 1
      ip: 127.0.0.1
      port: 6091