#################################################
# common
#################################################

mysql_1: &mysql_1
  host: ubuntu.a.com
  port: 3306
  user: root
  passwd: 1234
  schema: cx

#################################################
# server
#################################################

server:
  id: 1
  type: 1
  name: master
  listen:
    - id: 1
      ip: 127.0.0.1
      port: 6091
